### ISSUE TITLE
Ineffectual assignment (possible bug?)

### ISSUE THREAD

**Issue by cespare** [cznic/b#11]
Hey @cznic -- github.com/gordonklaus/ineffassign flagged this line as an ineffectual assignment: https://github.com/cznic/b/blob/6955404bf550e1eae1bf83121739078b027f4547/btree.go#L304

I haven't examined this closely enough to figure out whether the line can just be deleted or whether it's a bug.

**Comment by cznic** [comment]
Thanks for the report!

**Comment by cespare** [comment]
Thanks for the quick fix!
